units:
  c: 14 # Cherry MX switch cutout/hole length in mm
  s: 16 # Cherry MX switches are 15.6mm at their widest
  u: U # "U" was previously 19.05mm, but is now 19mm
points:
  zones.matrix:
    mirror:   
      ref: matrix_five_number
      distance: 6u
    key.tags.left: true
    key.mirror.tags:
      left: $unset
      right: true
    columns:
      zero:
        rows:
          meta:
            bind: [0, u/4, 0, u/4]
            shift: [-u/4, 0]
            spread: 1.5u
            width: 1.5u
            column_net: P18
            row_net: P8
            mirror.skip: true
          bottom:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P18
            row_net: P7
            mirror.skip: true
          home:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P18
            row_net: P6
            mirror.skip: true
          top:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P18
            row_net: P5
            mirror.skip: true
          number:
            shift: [u/4, 0]
            column_net: P18
            row_net: P4
            mirror.skip: true
      one:
        rows:
          meta:
            column_net: P15
            row_net: P8
            mirror.skip: true
          bottom:
            column_net: P15
            row_net: P7
            mirror:
              column_net: P8
              row_net: P18
          home:
            column_net: P15
            row_net: P6
            mirror:
              column_net: P8
              row_net: P19
          top:
            column_net: P15
            row_net: P5
            mirror:
              column_net: P8
              row_net: P20
          number:
            column_net: P15
            row_net: P4
            mirror:
              column_net: P8
              row_net: P21
      two:
        key.stagger: 3
        rows:
          meta:
            mirror.skip: true
            column_net: P14
            row_net: P8
          bottom:
            bind: 0
            column_net: P14
            row_net: P7
            mirror:
              column_net: P9
              row_net: P18
          home:
            column_net: P14
            row_net: P6
            mirror:
              column_net: P9
              row_net: P19
          top:
            column_net: P14
            row_net: P5
            mirror:
              column_net: P9
              row_net: P20
          number:
            column_net: P14
            row_net: P4
            mirror:
              column_net: P9
              row_net: P21
      three:
        key.stagger: 3
        rows:
          meta.skip: true
          bottom:
            bind: 0
            column_net: P16
            row_net: P7
            mirror:
              column_net: P10
              row_net: P18
          home:
            column_net: P16
            row_net: P6
            mirror:
              column_net: P10
              row_net: P19
          top:
            column_net: P16
            row_net: P5
            mirror:
              column_net: P10
              row_net: P20
          number:
            column_net: P16
            row_net: P4
            mirror:
              column_net: P10
              row_net: P21
      four:
        key.stagger: -3
        rows:
          meta.skip: true
          bottom:
            bind: 0
            column_net: P10
            row_net: P7
            mirror:
              column_net: P16
              row_net: P18
          home:
            column_net: P10
            row_net: P6
            mirror:
              column_net: P16
              row_net: P19
          top:
            column_net: P10
            row_net: P5
            mirror:
              column_net: P16
              row_net: P20
          number:
            column_net: P10
            row_net: P4
            mirror:
              column_net: P16
              row_net: P21
      five:
        key.stagger: -3
        rows:
          meta.skip: true
          bottom:
            bind: 0
            column_net: P9
            row_net: P7
            mirror:
              column_net: P14
              row_net: P18
          home:
            column_net: P9
            row_net: P6
            mirror:
              column_net: P14
              row_net: P19
          top:
            column_net: P9
            row_net: P5
            mirror:
              column_net: P14
              row_net: P20
          number:
            column_net: P9
            row_net: P4
            mirror:
              column_net: P14
              row_net: P21
    rows:
      meta:
      bottom:
      home:
      top:
      number:
  zones.extra:
    key.tags.right: true
    anchor:
      ref: matrix_five_bottom
      shift: [11u, 0]
    columns:
      minus:
        rows:
          bottom: # Blank (alternative backspace) key
            bind: [0, u/4, 0, u/4]
            shift: [u/4, 0]
            width: 1.5u
            column_net: P7
            row_net: P18
          home: # Double quotation mark key        
            bind: [0, u/4, 0, u/4]
            width: 1.5u
            column_net: P7
            row_net: P19
          top: # Opening square bracket key
            bind: 0
            shift: [-u/4, 0]
            column_net: P7
            row_net: P20
          number: # Minus key
            column_net: P7
            row_net: P21
      plus:
        rows:
          bottom: # Shift key
            bind: [0, u/4, 0, u/4]
            shift: [u/4, 0]
            width: 1.5u
            column_net: P6
            row_net: P18
          home: # Enter key        
            bind: [0, u/4, 0, u/4]
            width: 1.5u
            column_net: P6
            row_net: P19
          top: # Closing square bracket key
            bind: 0
            shift: [-u/4, 0]
            column_net: P6
            row_net: P20
          number: # Plus key
            column_net: P6
            row_net: P21
      backspace:
        rows:
          bottom.skip: true
          home.skip: true
          top: # Backslash key
            bind: [0, u/4, 0, u/4]
            shift: [u/4, 0]
            width: 1.5u
            column_net: P5
            row_net: P20
          number:  # Backspace key
            bind: [0, u/4, 0, u/4]
            width: 1.5u
            column_net: P5
            row_net: P21
    rows:
      bottom:
      home:
      top:
      number:
  zones.thumbcluster:
    mirror:   
      ref: thumbcluster_space_meta
      distance: 6u - 4
    key.tags.left: true
    key.mirror.tags:
      left: $unset
      right: true      
    anchor:
      ref: matrix_five_meta
      shift: [1.9, -5]
    columns:
      space.rows.meta:
        bind: [0, u/4, 0, u/4]
        splay: -15
        spread: 1.5u
        width: 1.5u
        column_net: P10
        row_net: P8
        mirror:
          column_net: P16
          row_net: P15
      mod.rows.meta:
        bind: [0, 1/4u, 0, 1/4u]
        shift: [1.15, -2.5] 
        splay: -10
        spread: 1.5u
        width: 1.5u
        column_net: P9
        row_net: P8
        mirror:
          column_net: P14
          row_net: P15
outlines:
  binding:
  - what: rectangle
    where: true
    size: u
    bound: true

  cutoutsleft:
  - what: rectangle
    where: left
    size: c

  cutoutsright:
  - what: rectangle
    where: right
    size: c

  switchesleft:
  - what: rectangle
    where: left
    fillet: 1
    size: s

  switchesright:
  - what: rectangle
    where: right
    fillet: 1
    size: s

  plateleft:
    - what: polygon
      points:
        - ref: matrix_zero_number
          shift: [-12 - u/2, 13 + 6]
        - ref: matrix_five_number
          shift: [48.4, 13 + 6]        
        - ref: matrix_five_bottom
          shift: [48.4, -32.3] 
        - ref: matrix_five_bottom
          shift: [39.447, -51.5]
        - ref: matrix_zero_meta
          shift: [-12 - u/4, -12]
    - what: rectangle
      where: left
      size: u

  plateright:
    - what: polygon
      points:
        - ref: mirror_matrix_five_number
          shift: [48.4, 13 + 6]
        - ref: extra_backspace_number
          shift: [12 + u/4, 13 + 6]
        - ref: extra_backspace_top
          shift: [12 + u/4, -30]
        - ref: extra_minus_bottom
          shift: [12 + u/2, -12  - 1u]
        - ref: mirror_matrix_five_bottom
          shift: [39.447, -51.5]
        - ref: mirror_matrix_five_bottom
          shift: [48.4, -32.3]          
    - what: rectangle
      where: right
      size: u

  left:
    - name: plateleft
    - name: switchesleft
      operation: stack
    - name: cutoutsleft
      operation: stack

  right:
    - name: plateright
    - name: switchesright
      operation: stack
    - name: cutoutsright
      operation: stack

  full:
    - name: left
    - name: right

  fullwithbounds:
    - name: full
    - name: binding
      operation: stack

# Example:
# https://github.com/MrCarney/mrkeyboard/blob/main/mrkeyboard.yaml
pcbs:
  left:
    outlines:
      plateleft.outline: plateleft
      keycaps:
        outline: switchesleft
        layer: Eco1.User
    footprints:

      # Any MX switch
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/mx.js
      mx:
        what: mx
        where: left
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/diode.js
      diode:
        what: diode
        where: left
        adjust:
          shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"

      # Arduino Pro Micro atmega32u4au
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/promicro.js
      promicro:
        what: promicro
        where:
          ref: matrix_five_number
          shift: [1u +1, -0.5]
          rotate: -90
        params:
          orientation: "down"

      # Reset button
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/button.js
      reset:
        what: button
        where:
          ref: matrix_five_top
          shift: [1u +1, -5]
        params:
          from: GND
          to: RST
          side: "B"

      # TRRS-PJ-320A-dual audio cable port
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/trrs.js
      trrs:
        what: trrs
        where:
          ref: matrix_five_number
          shift: [1u +1 +14.4 +5, 17]
        params:
          A: VCC
          B: P21
          C: P20
          D: GND
