units:
  c: 14 # Cherry MX switch cutout/hole length in mm
  s: 16 # Cherry MX switches are 15.6mm at their widest
  u: U # "U" was previously 19.05mm, but is now 19mm
points:
  zones.matrix:
    mirror:   
      ref: matrix_five_number
      distance: 6u
    key.tags.matrix: true
    key.mirror.tags:
      matrix: $unset
      right: true
    columns:
      zero:
        rows:
          meta:
            bind: [0, u/4, 0, u/4]
            shift: [-u/4, 0]
            spread: 1.5u
            width: 1.5u
            column_net: P1
            row_net: P9
            mirror.skip: true
          bottom:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P1
            row_net: P8
            mirror.skip: true
          home:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P1
            row_net: P7
            mirror.skip: true
          top:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P1
            row_net: P6
            mirror.skip: true
          number:
            shift: [u/4, 0]
            column_net: P1
            row_net: P5
            mirror.skip: true
      one:
        rows:
          meta:
            column_net: P0
            row_net: P9
            mirror.skip: true
          bottom:
            column_net: P0
            row_net: P8
            mirror.bind: 0
          home:
            column_net: P0
            row_net: P7
          top:
            column_net: P0
            row_net: P6
          number:
            column_net: P0
            row_net: P5
      two:
        key.stagger: 3
        rows:
          meta:
            mirror.skip: true
            column_net: P2
            row_net: P9
          bottom:
            bind: 0
            column_net: P2
            row_net: P8
          home:
            column_net: P2
            row_net: P7
          top:
            column_net: P2
            row_net: P6
          number:
            column_net: P2
            row_net: P5
      three:
        key.stagger: 3
        rows:
          meta.skip: true
          bottom:
            bind: 0
            column_net: P3
            row_net: P8
          home:
            column_net: P3
            row_net: P7
          top:
            column_net: P3
            row_net: P6
          number:
            column_net: P3
            row_net: P5
      four:
        key.stagger: -3
        rows:
          meta.skip: true
          bottom:
            bind: 0
            column_net: P4
            row_net: P8
          home:
            column_net: P4
            row_net: P7
          top:
            column_net: P4
            row_net: P6
          number:
            column_net: P4
            row_net: P5
      five:
        key.stagger: -3
        rows:
          meta.skip: true
          bottom:
            bind: 0
            column_net: P10
            row_net: P8
          home:
            column_net: P10
            row_net: P7
          top:
            column_net: P10
            row_net: P6
          number:
            column_net: P10
            row_net: P5
    rows:
      meta:
      bottom:
      home:
      top:
      number:
  zones.extra:
    key.tags.right: true
    anchor:
      ref: matrix_five_bottom
      shift: [11u, 0]
    columns:
      minus:
      plus:
        rows:
          bottom: # Shift key
            bind: [0, u/4, 0, u/4]
            shift: [u/4, 0]
            width: 1.5u
          home: # Enter key        
            bind: [0, u/4, 0, u/4]
            width: 1.5u
          top: # Backslash key
            bind: 0
            shift: [-u/4, 0]
      backspace:
        rows:
          bottom.skip: true
          home.skip: true
          top:
            bind: [0, u/4, 0, u/4]
            shift: [u/4, 0]
            width: 1.5u
          number:
            bind: [0, u/4, 0, u/4]
            width: 1.5u
    rows:
      bottom:
      home:
      top:
      number:
  zones.thumbcluster:
    mirror:   
      ref: thumbcluster_space_meta
      distance: 6u - 4
    key.tags.matrix: true
    key.mirror.tags:
      matrix: $unset
      right: true      
    anchor:
      ref: matrix_five_meta
      shift: [1.9, -5]
    columns:
      space.rows.meta:
        bind: [0, u/4, 0, u/4]
        splay: -15
        spread: 1.5u
        width: 1.5u
        column_net: P4
        row_net: P9
      mod.rows.meta:
        bind: [0, 1/4u, 0, 1/4u]
        shift: [1.15, -2.5] 
        splay: -10
        spread: 1.5u
        width: 1.5u
        column_net: P10        
        row_net: P9
outlines:
  binding:
  - what: rectangle
    where: true
    size: u
    bound: true

  cutoutsleft:
  - what: rectangle
    where: matrix
    size: c

  cutoutsright:
  - what: rectangle
    where: right
    size: c

  switchesleft:
  - what: rectangle
    where: matrix
    fillet: 1
    size: s

  switchesright:
  - what: rectangle
    where: right
    fillet: 1
    size: s

  plateleft:
    - what: polygon
      points:
        - ref: matrix_zero_number
          shift: [-12 - u/2, 13 + 6]
        - ref: matrix_five_number
          shift: [48.4, 13 + 6]        
        - ref: matrix_five_bottom
          shift: [48.4, -32.3] 
        - ref: matrix_five_bottom
          shift: [39.447, -51.5]
        - ref: matrix_zero_meta
          shift: [-12 - u/4, -12]
    - what: rectangle
      where: matrix
      size: u

  plateright:
    - what: polygon
      points:
        - ref: mirror_matrix_five_number
          shift: [48.4, 13 + 6]
        - ref: extra_backspace_number
          shift: [12 + u/4, 13 + 6]
        - ref: extra_backspace_top
          shift: [12 + u/4, -30]
        - ref: extra_minus_bottom
          shift: [12 + u/2, -12  - 1u]
        - ref: mirror_matrix_five_bottom
          shift: [39.447, -51.5]
        - ref: mirror_matrix_five_bottom
          shift: [48.4, -32.3]          
    - what: rectangle
      where: right
      size: u

  left:
    - name: plateleft
    - name: switchesleft
      operation: stack
    - name: cutoutsleft
      operation: stack

  right:
    - name: plateright
    - name: switchesright
      operation: stack
    - name: cutoutsright
      operation: stack

  full:
    - name: left
    - name: right

  fullwithbounds:
    - name: full
    - name: binding
      operation: stack

# Example:
# https://github.com/MrCarney/mrkeyboard/blob/main/mrkeyboard.yaml
pcbs:
  left:
    outlines.left.outline: left
    footprints:
      # Any MX switch
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/mx.js
      mx:
        what: mx
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
        where: left 
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/diode.js
      diode:
        what: diode
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        where: left
        adjust:
          shift: [0, -5]

      # Arduino ProMicro atmega32u4au
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/promicro.js
      promicro:
        what: promicro
        params:
          orientation: "up"
        where:
          ref: matrix_five_number
          shift: [22, -1]
          rotate: -90
      # Reset button
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/button.js
      reset:
        what: button
        where:
          ref: matrix_one_number
          shift: [0, 15]
        params:
          from: RST
          to: GND
      # TRRS-PJ-320A-dual audio cable port
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/trrs.js
      trrs:
        what: trrs
        where:
          ref: matrix_five_number
          shift: [38, 16.3]
        params:
          A: GND
          B: GND
          C: P21
          D: VCC
          reverse: false
          symmetric: false
