units:
  c: 14 # Cherry MX switch cutout/hole length in mm
  s: 16 # Cherry MX switches are 15.6mm at their widest
  u: U # "U" was previously 19.05mm, but is now 19mm
points:
  zones.matrix:
    anchor:
      shift: [121.525, -196.2]
    mirror:
      ref: matrix_five_number
      distance: 6u
    key.tags.left: true
    key.mirror.tags:
      left: $unset
      right: true
    columns:
      zero:
        rows:
          meta: # LCTRL
            bind: [0, u/4, 0, u/4]
            shift: [-u/4, 0]
            spread: 1.5u
            width: 1.5u
            column_net: P7
            row_net: P10
            mirror.skip: true
          bottom:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P7
            row_net: P16
            mirror.skip: true
          home:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P7
            row_net: P14
            mirror.skip: true
          top:
            bind: [0, u/4, 0, u/4]
            spread: 1.5u
            width: 1.5u
            column_net: P7
            row_net: P15
            mirror.skip: true
          number:
            shift: [u/4, 0]
            column_net: P7
            row_net: P18
            mirror.skip: true
      one:
        rows:
          meta: # CODE / Super
            column_net: P8
            row_net: P10
            mirror.skip: true
          bottom:
            column_net: P8
            row_net: P16
            mirror:
              column_net: P16
              row_net: P8
          home:
            column_net: P8
            row_net: P14
            mirror:
              column_net: P16
              row_net: P7
          top:
            column_net: P8
            row_net: P15
            mirror:
              column_net: P16
              row_net: P6
          number:
            column_net: P8
            row_net: P18
            mirror:
              column_net: P16
              row_net: P5
      two:
        key.stagger: 3
        rows:
          meta: # LALT
            mirror.skip: true
            column_net: P9
            row_net: P10
          bottom:
            bind: 1
            column_net: P9
            row_net: P16
            mirror:
              column_net: P10
              row_net: P8
          home:
            column_net: P9
            row_net: P14
            mirror:
              column_net: P10
              row_net: P7
          top:
            column_net: P9
            row_net: P15
            mirror:
              column_net: P10
              row_net: P6
          number:
            column_net: P9
            row_net: P18
            mirror:
              column_net: P10
              row_net: P5
      three:
        key.stagger: 3
        rows:
          meta.skip: true
          bottom: # C
            bind: 0
            column_net: P21
            row_net: P16
            mirror:
              column_net: P2
              row_net: P8
          home:
            column_net: P21
            row_net: P14
            mirror:
              column_net: P2
              row_net: P7
          top:
            column_net: P21
            row_net: P15
            mirror:
              column_net: P2
              row_net: P6
          number:
            column_net: P21
            row_net: P18
            mirror:
              column_net: P2
              row_net: P5
      four:
        key.stagger: -3
        rows:
          meta.skip: true
          bottom: # V
            bind: 0
            column_net: P20
            row_net: P16
            mirror:
              column_net: P3
              row_net: P8
          home:
            column_net: P20
            row_net: P14
            mirror:
              column_net: P3
              row_net: P7
          top:
            column_net: P20
            row_net: P15
            mirror:
              column_net: P3
              row_net: P6
          number:
            column_net: P20
            row_net: P18
            mirror:
              column_net: P3
              row_net: P5
      five:
        key.stagger: -3
        rows:
          meta.skip: true
          bottom: # B
            bind: 0
            column_net: P19
            row_net: P16
            mirror:
              column_net: P4
              row_net: P8
          home:
            column_net: P19
            row_net: P14
            mirror:
              column_net: P4
              row_net: P7
          top:
            column_net: P19
            row_net: P15
            mirror:
              column_net: P5
              row_net: P6
          number:
            column_net: P19
            row_net: P18
            mirror:
              column_net: P4
              row_net: P5
    rows:
      meta:
      bottom:
      home:
      top:
      number:
  zones.extra:
    key.tags.right: true
    anchor:
      ref: matrix_five_meta
      shift: [11u, 0]
    columns:
      minus:
        rows:
          meta: # Backspace
            bind: [0, u/4, 0, u/4]
            shift: [u/4, 0]
            width: 1.5u
            column_net: P18
            row_net: P5
          bottom: # Blank (alternative backspace)
            shift: [-u/4, 0]
            column_net: P14
            row_net: P8
          home: # Double quotation mark
            column_net: P14
            row_net: P7
          top: # Opening square bracket
            column_net: P14
            row_net: P6
          number: # Minus key
            column_net: P14
            row_net: P5
      plus:
        rows:
          meta.skip: true
          bottom: # Shift
            column_net: P15
            row_net: P8
          home: # Enter
            column_net: P15
            row_net: P7
          top: # Closing square bracket
            column_net: P15
            row_net: P6
          number: # Plus
            column_net: P15
            row_net: P5
    rows:
      meta:
      bottom:
      home:
      top:
      number:
  zones.thumbcluster:
    anchor:
      ref: matrix_four_bottom
      shift: [-3.45, -1u -3]
    key.tags.left: true
    key.mirror.tags:
      left: $unset
      right: true
    mirror:
      ref: mirror_matrix_five_bottom
      distance: -6u
    columns:
      three.rows.meta: # Backspace
        splay: -18.925
        column_net: P19 #TBD
        row_net: P10 #TBD
        mirror:
          column_net: P4 #TBD
          row_net: P9 #TBD
      four.rows.meta: # Space
        bind: [0, u/4, 0, u/4]
        spread: 1.25u
        width: 1.5u
        column_net: P20
        row_net: P10
        mirror:
          column_net: P3
          row_net: P9
      five.rows.meta: # Mod
        shift: [u/4, -0]
        column_net: P19
        row_net: P10
        mirror:
          column_net: P4
          row_net: P9

outlines:
  bindingleft:
    - what: rectangle
      where: left
      size: u
      bound: true

  bindingright:
    - what: rectangle
      where: right
      size: u
      bound: true

  cutoutsleft:
    - what: rectangle
      where: left
      size: c

  cutoutsright:
    - what: rectangle
      where: right
      size: c

  switchesleft:
    - what: rectangle
      where: left
      fillet: 1
      size: s

  switchesright:
    - what: rectangle
      where: right
      fillet: 1
      size: s

  wallsleft:
    - what: polygon
      points:
        - ref: matrix_zero_number
          shift: [-u/2 -u, u/2 +6]
        - ref: matrix_five_number
          shift: [u + 15.6, u/2 +6]
        - ref: matrix_five_bottom
          shift: [u + 15.6, -1u -1/2u]
        - ref: matrix_zero_meta
          shift: [-u/4 -u, -u/2]

  wallsright:
    - what: polygon
      points:
        - ref: mirror_matrix_five_number
          shift: [u + 15.6, u/2 +6]
        - ref: extra_plus_number
          shift: [u/2, u/2 +6]
        - ref: extra_plus_bottom
          shift: [u/2, -u/2 -u]
        - ref: mirror_matrix_five_bottom
          shift: [u + 15.6, -u -1/2u]

  left:
    - name: bindingleft
      operation: stack
    - name: wallsleft
      operation: stack
    - name: switchesleft
      operation: stack
    - name: cutoutsleft
      operation: stack

  right:
    - name: bindingright
      operation: stack
    - name: wallsright
      operation: stack
    - name: switchesright
      operation: stack
    - name: cutoutsright
      operation: stack

  full:
    - name: left
      operation: stack
    - name: right
      operation: stack

# Example:
# https://github.com/MrCarney/mrkeyboard/blob/main/mrkeyboard.yaml
pcbs:
  left:
    outlines:
      wallsleft.outline: wallsleft
      keycaps:
        outline: switchesleft
        layer: Eco1.User
      binding:
        outline: bindingleft
        layer: Eco2.User

    footprints:
      # Any MX switch
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/mx.js
      mx:
        what: mx
        where: left
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      # Nexperia CFP3 (SOD-123W) SMD diode
      diode:
        what: diode # TODO change to sod-123w
        where: left
        adjust:
          shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"

      # Arduino Pro Micro atmega32u4au
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/promicro.js
      promicro:
        what: promicro
        where:
          ref: matrix_five_number
          rotate: -90
          shift: [1u +1, 0.65]
        params:
          orientation: "down"

      # Reset button
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/button.js
      reset:
        what: button
        where:
          ref: matrix_five_top
          rotate: -90
          shift: [1u +1, -5]
        params:
          from: GND
          to: RST
          side: "B"

      # TRRS-PJ-320A-dual audio cable port
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/trrs.js
      # https://keeb.io/products/trrs-jack-3-5mm
      trrs:
        what: trrs
        where:
          ref: matrix_five_number
          shift: [1u +15.6 + 5, 17.95]
        params:
          A: GND # 1
          B: GND # 2
          C: VCC # 3
          D: P0 # 4
          reverse: true
          # Symmetric only works for the "Serial" pinout
          symmetric: true
  right:
    outlines:
      wallsright.outline: wallsright
      keycaps:
        outline: switchesright
        layer: Eco1.User
      binding:
        outline: bindingright
        layer: Eco2.User

    footprints:
      # Any MX switch
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/mx.js
      mx:
        what: mx
        where: right
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      # Nexperia CFP3 (SOD-123W) SMD diode
      diode:
        what: diode # TODO change to sod-123w
        where: right
        adjust:
          shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"

      # Arduino Pro Micro atmega32u4au
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/promicro.js
      promicro:
        what: promicro
        where:
          ref: mirror_matrix_five_number
          rotate: 90
          shift: [1u +1, 0.65]
        params:
          orientation: "down"

      # Reset button
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/button.js
      reset:
        what: button
        where:
          ref: mirror_matrix_five_top
          rotate: 90
          shift: [1u +1, -5]
        params:
          from: GND
          to: RST
          side: "B"

      # TRRS-PJ-320A-dual audio cable port
      # https://github.com/ergogen/ergogen/blob/develop/src/footprints/trrs.js
      # https://keeb.io/products/trrs-jack-3-5mm
      trrs:
        what: trrs
        where:
          ref: mirror_matrix_five_number
          shift: [1u + 11 + 5, 17.95]
        params:
          A: GND # 1
          B: GND # 2
          C: VCC # 3
          D: P0 # 4
          reverse: true
          # Symmetric only works for the "Serial" pinout
          symmetric: true
